# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - qoptportfolio

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://qportfolioopt.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_aa8fdb70611b4328b7b2c3cbad614a79 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3f629b7ea3894150be26d0ed5dfb931e }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: qportfolioopt.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_aa8fdb70611b4328b7b2c3cbad614a79 }}/portfolio_opt-final_streamlit:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'qoptportfolio'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d89c0d60053247f59eb559f67e102754 }}
        images: 'qportfolioopt.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_aa8fdb70611b4328b7b2c3cbad614a79 }}/portfolio_opt-final_streamlit:${{ github.sha }}'